### ISSUE TITLE
change the way application inventory is created

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/twoliter#140]
The build produces a JSON where packages are represented like this:

We need to consider what this looks like when some packages are coming from the OOTB project and some from kits (or the alpha SDK). Basically we need to track down how this produced and decide how it needs to look based on downstream requirements.

```json
    {
      "Name": "systemd",
      "Publisher": "Bottlerocket",
      "Version": "1.18.0",
      "Release": "ad294c88-dirty",
      "InstalledTime": "2024-01-24T22:00:21Z",
      "ApplicationType": "Unspecified",
      "Architecture": "aarch64",
      "Url": "https://www.freedesktop.org/wiki/Software/systemd",
      "Summary": "System and Service Manager"
    }
```

**Comment by ginglis13** [comment]
In order to support generation of valid Bottlerocket updateinfo.xml with the introduction of kits, we could use the following changes to application-inventory.json:

* an `epoch` field, computed as the revision count from git history of the source project for the package
* the `version` of a package is the package's version, no longer the Bottlerocket release version

The `epoch` field would be necessary because of changes to the `version` field. Bottlerocket versions and package versions may conflict in updateinfo.xml, so the `epoch` can be used to convey that a new package update is required.

This results in an application-inventory.json shape like

```json
{
  [
    {
      "Name": "glibc",
      "Publisher": "Bottlerocket",
      # This is now the package version
      "Version": "2.38.0",
      # This is (still) the Git hash of the latest tag
      "Release": "fcf71a47c",
      # This is the revision count of the latest tag
      "Epoch": "6792",
      "InstalledTime": "2024-05-09T14:13:10Z",
      "ApplicationType": "Unspecified",
      "Architecture": "x86_64",
      "Url": "http://www.gnu.org/software/glibc/",
      "Summary": "The GNU libc libraries"
    }
  ]
}
```

This could be done similar to the following

* Twoliter calculates `epoch` from the git metadata, falling back to `0` if unset. (maybe also override this by an environment variable)
* Pass the epoch value into buildsys. In Dockerfile, prepend this value as the `Epoch` field in spec files.
* Write out the `epoch` field in application-inventory.json.
* Write out the actual package version in application-inventory.json, now that reuse of prior versions doesn’t matter.

I'm curious to hear thoughts on this, as well as potentially changing the `Publisher` field value to that of kit `vendor` in a Twoliter project file, the vendor of the kit that included this package.

**Comment by ginglis13** [comment]
A better approach than the above for this might be to instead modify the `"Release"` field from git short sha of the latest commit at build time to the `<monotonically_increasing_id>+<git_short_sha>`. The `<monotonically_increasing_id>` is essentially what the `"Epoch"` field attempts to achieve. The value for this id can be the unix timestamp in ms of the latest commit (`git show -s --format=%ct <mytagname>^{commit}`). This would avoid "wasting" the use of an `epoch` in updateinfo.xml if for some reason in the future, it is necessary to supply one for an update.

We'll keep the `"Publisher"` as Bottlerocket for now, but this may change in the future if requirements for kit publishers being the "Publisher" happen.

We'll still need the `"Version"` field to be the package's actual version going forward.
